### ISSUE TITLE
Explosión de un servidor.

### ISSUE THREAD

**Issue by zalaya** [Danilop95/Fail2Ban-QuickSetup#1]
Buenas, tengo una startup dedicada a servidores, he ejecutado esto en mi ordenador para probar y justo despues a la ejecución todos los servidores de la compañía han comenzado a apagarse y encenderse. Trás eso un compañero ha ido a revisar por si había una falla en algún script de los que tenemos y uno de los servidores cercanos a el ha explotado. Esta en coma y todo ha sido culpa de usted, solicitamos una indemnización cuanto antes.

**Comment by Danilop95** [comment]
El problema reside en que no ha realizado el pago por minuto de 3€ para que esto no suceda, se que puede ser algo complicado pero intente hacer el esfuerzo por favor

**Comment by Danilop95** [comment]
OTRO CLIENTE SATIFECHO
